### ISSUE TITLE
Can't fly after joining arena

### ISSUE THREAD

**Issue by EpicJosch** [Ajneb97/MineChess#10]
When i join an arena then i can't fly. I know that this is because the arena is in another world than the lobby because when i went to the  arena world and then joined the arena i was able to fly. And i have a feeling i know what the problem is: When im right then you are using this code to let the player join your arena:

https://management.azrasoul.de/s/k7QLS5KAgNGfRQf

You first set the player flying and then teleport the player to the arena. Since 1.18 this doesn't work because minecraft disables the flight on any world change.

Because of that i would be really happy if you could change this so the player is first teleported to the arena and then set to flight.

**Comment by Ajneb97** [comment]
I never had any issues with flight testing even in spigot 1.20. Do you use Multiverse Core? If so, enable the option allow-flight in the config of that world.

**Comment by EpicJosch** [comment]
Yeas i use Multiverse Core. But allow-flight is already enabled

**Comment by EpicJosch** [comment]
Workaround by turning on FLY in the arena region with the Plugin [WorldGuardExtraFlags](https://www.spigotmc.org/resources/worldguard-extra-flags.4823/)

--> TIP: When you have bypass permissions (worldguard.region.bypass.<world> or Owner of the region) then the Flags of the Plugin [WorldGuardExtraFlags](https://www.spigotmc.org/resources/worldguard-extra-flags.4823/) are not applied to you (so you can't fly in this case)!
